### ISSUE TITLE
Search index doesn't seem to show the default _score sorting

### ISSUE THREAD

**Issue by bluedigitaldevteam** [monsieurbiz/SyliusSearchPlugin#107]
Hi,

Issue:

I've got a problem with the default search result ordering. The default order doesn't seem to be using the 'scores' or showing the correct relevancy. For example - I'm getting description/attribute matches above the name matches.

Details:

Example products:
1: {name: One Word}
2: {name: Two Word}

When searching for keywords '_Two Word_', I would expect both products to show, but for product:2 to show first as it's a direct match on the 'name' field.

I've tried and tested a few things but nothing seems to work, I can override the sorting with the grid sorting parameters (a-z, createdAt etc), but the default sorting doesn't seem right. I'm getting a handful of products with (Sylius) attribute or 'description' matches before a 'name' match, and in some cases it seems I get a half match (matching just 'Two' in the description) showing above a full match of 'Two Word' in the name.

I've checked my theme and src/ customisations and even after removing them, the default order still appears to be incorrect.
I then tried to customise things further (DocumentableTrait, Document, search.yaml, analyzer.yaml) but nothing seems to work, even bringing the 'name' into a top-level field and trying to sort/boost it did nothing. 

One thing I've not been able to confirm is the top-level _score's for each result as it seems php/twig doesn't have access to this info so I am making some assumptions about weight/score/boost. I've also not been able to confirm what the actual default sorting is, I thought maybe it was the 'position' but I wasn't able to confirm this and it's not anything obvious like a-Z unless there's additional sorting on top.

I've been through the docs/code of jolicode/elastically and ruflin/Elastica and I can't find anything useful there either. Based on everything I've read, what I want should be the default so I'm just confused.

Could it be some other Sylius customisation I've done getting in the way? Is this something that is maybe not in the Issues but was known and has been fixed post 0.2.6? I noticed the search.yml is very different in the later versions.

Any thoughts of what I could be missing or need to check?

**Comment by bluedigitaldevteam** [comment]
I think I have a fix for my use-case but I'm not sure how correct this is.

It seems like there's two changes needed - the first is that `track_scores: true` has to be set on the root level (next to query/sort/filter etc, see:https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html#_track_scores) and the second is that the 'default' sort via the `SortHelper` seems wrong.

This is the default:
```
"sort" => array:1 [▼
  0 => array:1 [▼
    "attributes.value.keyword" => array:2 [▼
      "order" => "desc"
      "nested" => array:2 [▼
        "path" => "attributes"
        "filter" => array:1 [▼
          "term" => array:1 [ …1]
        ]
      ]
    ]
  ]
]
```
this is the customised one to use `_score`
```
"sort" => array:1 [▼
  0 => array:1 [▼
    "_score" => array:1 [▼
      "order" => "desc"
    ]
  ]
]
```

I've hacked these locally which seems to solved my sorting issues but I'm not sure how best to override/fix these long term. Do you have any recommendations?

I also noticed the `master` branch has a new `search.yaml` which still provides accurate results but there is a difference to the order/scoring. I'll play around and see which one fits my needs long term (I did also add a custom change to go direct to a product if a `code` or `name` was matched 100% with a `term` check.

**Comment by maximehuran** [comment]
Done in v2 you will be able to choose your sorting and manage boosts.
We will add documentation about this part soon.
