### ISSUE TITLE
Tests are failing but action is green

### ISSUE THREAD

**Issue by lruozzi9** [monsieurbiz/SyliusSearchPlugin#119]
The only "test" existing on this repo is given by the static analysis of the code by phpstan, and it fails (https://github.com/monsieurbiz/SyliusSearchPlugin/runs/5213105819?check_suite_focus=true)... But the action goes green. Something is not well configured.

**Comment by maximehuran** [comment]
Closed by https://github.com/monsieurbiz/SyliusSearchPlugin/pull/172
