### ISSUE TITLE
Class "MonsieurBiz\SyliusSearchPlugin\Model\Document\Index\AbstractIndex" not found while loading "MonsieurBiz\SyliusSearchPlugin\Model\Document\Index\Indexer".

### ISSUE THREAD

**Issue by camilleislasse** [monsieurbiz/SyliusSearchPlugin#128]
https://github.com/monsieurbiz/SyliusSearchPlugin/blob/cf46d7ba22d01ef48cbcb2916969b375894ff3e9/src/Model/Document/Index/Indexer.php#L28

 Class "MonsieurBiz\SyliusSearchPlugin\Model\Document\Index\AbstractIndex" not found while loading "MonsieurBiz\SyliusSearchPlugin\Model\Document\Index\Indexer".

**Comment by delyriand** [comment]
Hi @camilleislasse!

It's a mistake, the class `MonsieurBiz\SyliusSearchPlugin\Model\Document\Index\Indexer` is not used in plugin v2.
I try to do a PR and a release during the day.

PHPCS and PHPMD errors should be corrected (cf #119)

Thx
