### ISSUE TITLE
Variable "event_prefix" does not exist.

### ISSUE THREAD

**Issue by vasilvestre** [monsieurbiz/SyliusSearchPlugin#203]
When rendering admin settings and opening SyliusSearchPlugin, a template miss a variable.

![image](https://github.com/monsieurbiz/SyliusSearchPlugin/assets/17164385/b733c2c7-fd96-4a88-a125-21ad0793fb8a)

Versions

|package|version|
|------------|--------|
|   Symfony  |   5.4  |
|   Sylius   |1.12.13 |
|SyliusSearch| 2.1.8  |
|SyliusSettings| 1.1.1 |

**Comment by delyriand** [comment]
Hi @vasilvestre!

This error is not related to the Search plugin, nor is it totally related to the Settings plugin…

You have overridden the template to add `{{ sylius_template_event([event_prefix ~ '.buttons'...`, except that this template can be used without the variable being defined.

For example, you should get the same error if you try to edit the addresses of an order (example: `/admin/orders/XXX/edit`).

One solution would be to define a default value just in case:
```
{{ sylius_template_event([event_prefix|default('global' ~ '.buttons'...
```

**Comment by vasilvestre** [comment]
I guess a coffee was required

Sorry for the noise 😅

**Comment by delyriand** [comment]
you will buy me a beer during the afup day 🍻  ;)
