### ISSUE TITLE
Version 2.1 doesn't support new Sylius version 1.13

### ISSUE THREAD

**Issue by GuiForce** [monsieurbiz/SyliusSearchPlugin#207]
Hello,
We must upgrade our Sylius version to the most recent: 1.13.
But after upgrading, the composer's update does not work because Monsiebiz / Sylius-Search-Plugin requires Sylius> = 1.9 & <1.13
Is there an upgrade planned soon?
Thanks

**Comment by nicolas-joubert** [comment]
Bump. Any news about upgrade @etienne-monsieurbiz ?

**Comment by maximehuran** [comment]
Hi,

We are upgrading our plugins one by one. We have planned to do it, but we have not scheduled a specific date yet.

Feel free to create a pull request with the upgrade. You can find an example of the CMS Page upgrade here: https://github.com/monsieurbiz/SyliusCmsPagePlugin/pull/70

Also, regarding the dependencies, we need to upgrade the Sylius Settings Plugin to be compatible with Sylius 1.13 first.

**Comment by maximehuran** [comment]
Sylius Settings Plugin is now available for Sylius 1.13

https://github.com/monsieurbiz/SyliusSettingsPlugin/releases/tag/v1.2.0

The Search plugin will follow soon

**Comment by nicolas-joubert** [comment]
Great, thanks.

**Comment by maximehuran** [comment]
You can check this PR, after that we will release the `2.2.0` version of the plugin : 

https://github.com/monsieurbiz/SyliusSearchPlugin/pull/215
