### ISSUE TITLE
Missing variable

### ISSUE THREAD

**Issue by nayluge** [monsieurbiz/SyliusSearchPlugin#22]
<img width="726" alt="Capture d’écran 2020-05-22 à 11 11 00" src="https://user-images.githubusercontent.com/7482831/82652061-4f801480-9c1d-11ea-82d7-ab1fbf78dc72.png">

Just updated the bundle and got this error

**Comment by jacquesbh** [comment]
It is because you didn't update your configuration file with the correct content:
https://github.com/monsieurbiz/SyliusSearchPlugin/blob/6635bb298defac35b765b0b355abd7c11b37ef19/recipe/dev/config/packages/monsieurbiz_sylius_search_plugin.yaml#L25-L38

I've made a PR to change this requirement.
