### ISSUE TITLE
Default sorting on Taxon is not following the product position in taxons

### ISSUE THREAD

**Issue by nayluge** [monsieurbiz/SyliusSearchPlugin#26]
Imo, the default behavior on taxon should be to follow the order defined in the back-office

**Comment by maximehuran** [comment]
Corrected on master : 

https://github.com/monsieurbiz/SyliusSearchPlugin/compare/7babbf784d9248cc8007b6778e6a6a644e79d61b...3fee3438cb72321336858fda39bf6776003a012c
