### ISSUE TITLE
Manage filters from the admin panel

### ISSUE THREAD

**Issue by shurco** [monsieurbiz/SyliusSearchPlugin#28]
How can I implement control, on and off, setting the order in which filters are displayed in the admin panel?
Setting up through configuration files is not very convenient, and if the site has several different sections of the catalog, big problems arise. ((

**Comment by jacquesbh** [comment]
Hi @shurco!

We will implement this feature this week probably. I'll stay in touch!

Thank you.

**Comment by jacquesbh** [comment]
@shurco You could use the PR I've just made. It's not released yet, be aware of that.

You may need a small fix in your migrations as well: https://github.com/monsieurbiz/SyliusSearchPlugin/pull/30

Have fun!

**Comment by shurco** [comment]
Ok, thanks !!
