### ISSUE TITLE
The package phpdocumentor/reflection-docblock is not found in the prod env

### ISSUE THREAD

**Issue by htaoufikallah** [monsieurbiz/SyliusSearchPlugin#34]
in order to use the bin/console monsieurbiz:search:populate command in prod env the package phpdocumentor/reflection-docblock is required to avoid the thrown exception check this PR
https://github.com/symfony/symfony/pull/26265
I think this note should be added to the doc, WYT?

**Comment by jacquesbh** [comment]
I find this pretty strange. Are you sure it's not related to your environment?

Can you give me on which version of Sylius you are?

Thanks

**Comment by htaoufikallah** [comment]
I got this error on ubuntu server 18.04 and on my Mac book pro mujave
Sylius version is 1.7.6
I use [https://deployer.org/](https://deployer.org/) for deployment here is the composer command that is used to install dependencies:
`composer install --verbose --prefer-dist --no-progress --no-interaction --no-dev --optimize-autoloader --no-suggest`
[https://github.com/deployphp/deployer/blob/master/recipe/common.php#L87](https://github.com/deployphp/deployer/blob/master/recipe/common.php#L87)

Did you try to remove the vendor directory and set env to prod and then reinstall dependencies?

**Comment by jacquesbh** [comment]
Will do :-)

Thanks, I'll let you know. Unfortunately we can't test this before end of
next week.

This is still strange because it works well for us. I'll have a better look
next week.

Jacques Bodin-Hullin

-- 
Monsieur Biz
@jacquesbh
+33 (0)6 75 54 11 97
GPG : https://keybase.io/jacquesbh

🦄

**Comment by jacquesbh** [comment]
What are the other custom.packages that you installed?

Jacques Bodin-Hullin

-- 
Monsieur Biz
@jacquesbh
+33 (0)6 75 54 11 97
GPG : https://keybase.io/jacquesbh

🦄

**Comment by htaoufikallah** [comment]
I just test it on a clean project with sylius 1.7.6 and I got the same error, here are the dependencies:
```
"require": { 
        "php": "^7.3", 
        "sylius/sylius": "~1.7.0", 
        "symfony/dotenv": "^4.4", 
        "symfony/flex": "^1.2", 
        "monsieurbiz/sylius-search-plugin": "dev-master"
}
```

**Comment by lamasfoker** [comment]
I get the same error in prod env. I think that it is a jolicode/elastically issue. This have to declare phpdocumentor/reflection-docblock as a require instead of a require dev.
If you think that is a symfony/property-info issue like someone said [here](https://github.com/symfony/symfony/issues/26259#issue-299034570), you can see the dev response [here](https://github.com/symfony/symfony/pull/26260#issuecomment-367632239)

**Comment by damienalexandre** [comment]
I think this is related to https://github.com/monsieurbiz/SyliusSearchPlugin/commit/99aafd2f07503a92dbc4cb441d40c26ca42fa22a as now you rely on a static Serializer created here:

https://github.com/jolicode/elastically/blob/9632716ac0b4eada85271c64b9586d841fd532fb/src/Client.php#L97-L112

I don't like very much this default Serializer in Elastically and suggest you move away from it by injecting an explicit serializer, I may be requiring this in the future.

Cheers!

**Comment by maximehuran** [comment]
Closed with elastically update
