### ISSUE TITLE
Add Italian localization

### ISSUE THREAD

**Issue by lamasfoker** [monsieurbiz/SyliusSearchPlugin#36]
It's possible to add italian localization? I see a todo in this file src/Resources/config/services.yaml

**Comment by jacquesbh** [comment]
Hi!

You can create a PR if you want!
We don't speak italian unfortunately.

**Comment by mmenozzi** [comment]
I think @lamasfoker meant adding ElasticSearch index mapping for italian locale. Or more generally speaking what's the workflow to customize the ElasticSearch mapping.

**Comment by jacquesbh** [comment]
Closed by #37.

**Comment by jacquesbh** [comment]
@mmenozzi This plugin is not yet stable and needs more documentation. Right now you have to write your own files and change the DI for the service: https://github.com/monsieurbiz/SyliusSearchPlugin/blob/master/src/Resources/config/services.yaml#L34-L47

This is why we have a `TODO` on this :p.

**Comment by mmenozzi** [comment]
Great! Thank you!
