### ISSUE TITLE
[QUESTION] Support for elasticsearch 7.8.0

### ISSUE THREAD

**Issue by lamasfoker** [monsieurbiz/SyliusSearchPlugin#38]
In the README I read:

> The plugin was developed for Elasticsearch 7.2.x versions.

Is this the only version supported or the only version tested?
It is safe to use the latest version of elasticsearch the 7.8.0?

**Comment by jacquesbh** [comment]
We only test the plugin on ES 7.2.x.
I think it should work on 7.8, but I can't be sure.

Could you try it?

Thank you!

**Comment by lamasfoker** [comment]
I confirm that the plugin works also with ES 7.8.0

Thank you
