### ISSUE TITLE
The populate input is not customizable

### ISSUE THREAD

**Issue by Nek-** [monsieurbiz/SyliusSearchPlugin#48]
I started to talk about repository in another issue ( https://github.com/monsieurbiz/SyliusSearchPlugin/issues/46 ) but I forget to mention something. Using `findAll` and only doctrine repositories is an issue. It should actually use an interface like this:

```php
interface SearchRepository // this name is broken, you can do better
{
    public function findItemsToPopulate();
}
```

But well, #47 suggests also that things should be rethought at a higher level. This issue is relevant to keep the problem in mind.

**Comment by maximehuran** [comment]
We are using `DatasourceInterface` for that in v2
