### ISSUE TITLE
[Question]How to define own search criteria.

### ISSUE THREAD

**Issue by atapatel** [monsieurbiz/SyliusSearchPlugin#56]
Hello i have one custom requirement, I need to create separate search criteria, just like `search` `instant` `taxons`. How can I create one?

**Comment by maximehuran** [comment]
Can you give more details please ? 

- What is the use case ?
- Can we have some examples ?

**Comment by maximehuran** [comment]
Feel free to read the documentation here : 

https://github.com/monsieurbiz/SyliusSearchPlugin/blob/master/docs/index.md
