### ISSUE TITLE
In template the currency is not converted

### ISSUE THREAD

**Issue by lamasfoker** [monsieurbiz/SyliusSearchPlugin#57]
### Bug
In the file `SyliusSearchPlugin/src/Resources/views/Common/_box.html.twig` to display the price of the results is used `money.format()`. In this way if the currency is different from the default one of the channel, the amount is not converted.

### Solution
Use the macro `money.convertAndFormat()` instead, as sylius does internally with the macro `money.calculatePrice()`

**Comment by jacquesbh** [comment]
Closed by #71
