### ISSUE TITLE
Error Adding new products

### ISSUE THREAD

**Issue by Lozkho** [monsieurbiz/SyliusSearchPlugin#61]
After installing the plugin in local server (Xampp) and VPS (UIbuntu), adding a new product from Admin Panel generates this error:

> Cannot find a field on 'App\Entity\Channel\ChannelPricing' that is mapped to column 'channelCode'. Either the field does not exist or an association exists but it has multiple join columns.

Using Sylius 1.6.8,  What it can be?

**Comment by jacquesbh** [comment]
Hi!

Can you provide the full trace please? (in your logs probably)

Thank you!
