### ISSUE TITLE
Impossible to search taxons

### ISSUE THREAD

**Issue by Roshyo** [monsieurbiz/SyliusSearchPlugin#66]
Currently, the plugin README specifies that we can add any model to the search index by adding the `DocumentableInterface`
But then when doing so, we end up with an error thrown by `public function getUrlParams(): UrlParamsProvider` in `Result` class.

We would need a way to update this switch/case or provide a way to change this URLParamsProvider. Perhaps with another method in the Result class ?

**Comment by maximehuran** [comment]
Maybe this merged pull request answer to your issue ? 

https://github.com/monsieurbiz/SyliusSearchPlugin/pull/77

**Comment by maximehuran** [comment]
Our new test App also index Taxons, check the documentation available form 2.1.x : 

https://github.com/monsieurbiz/SyliusSearchPlugin/blob/master/docs/add_custom_entities.md

Upgrade guide : 

https://github.com/monsieurbiz/SyliusSearchPlugin/blob/master/UPGRADE-2.0.md
