### ISSUE TITLE
How to create custom logic behind showing all product.

### ISSUE THREAD

**Issue by atapatel** [monsieurbiz/SyliusSearchPlugin#73]
I have been using this plugin for the last 3 months and I admit it is really nice. I am going to add one complex feature in the eCommerce portal, e.g *Create all product listing page with facets.* Can anyone here suggest or show me a way to do it? Again thanks in adavance.

**Comment by jacquesbh** [comment]
Hi!

I suggest adding a new request to elasticsearch using elastically.

It's a feature we would like to have as well but it's not in our planning at the moment :/.

**Comment by maximehuran** [comment]
This is very specific case and the plugin will not manage it.
You can create your own route or create a taxon with all product ?
