### ISSUE TITLE
Add custom fields to taxon filters

### ISSUE THREAD

**Issue by costa-jeremy** [monsieurbiz/SyliusSearchPlugin#80]
Hello everyone,

I have been using the plugin for some time and I admit that it is very nice ! 

However i a currently blocked,  indeed I would like to add a custom field to the Taxons filters (in my case the brand) but it seems that this is not currently possible easily.

 Anyone would have a solution for this?

Thank you !

**Comment by maximehuran** [comment]
We have to look on GridConfig class, we have this method to retrieve filters : 

```
/**
     * @return string[]
     */
    public function getFilters(): array
    {
        return array_merge($this->getAttributeFilters(), $this->getOptionFilters());
    }
```

But @Costa-Jeremy tried it and the custom filter was not displayed. Maybe we have other things to change to display it.
We have to add a way to configure some custom fields that we want to display as filter. (Not option, not attribute)

**Comment by jacquesbh** [comment]
You can add your brand using a new fake attribute (only in the Document, not in the real product):
https://github.com/monsieurbiz/SyliusSearchPlugin/blob/85ac2779817d98d618430cba6315ea2ebe008808/src/Model/Documentable/DocumentableProductTrait.php#L57-L60

Then you can add this "attribute" as a filter in this method:
https://github.com/monsieurbiz/SyliusSearchPlugin/blob/85ac2779817d98d618430cba6315ea2ebe008808/src/Model/Config/GridConfig.php#L245-L259

So, you may need to change the GridConfig via a new service in the DI.
Then you can override the method in your Product entity to add the new attribute into the Document.

It should do the trick.
But I agree with Maxime, we need to fire some events here to allow some new filters, or maybe using some configuration…

**Comment by Costa-Jeremy** [comment]
Hello,

Thanks for the answers.

As said @maximehuran , i have already tested to add attributes in this function, but that did not work

$this->filterableAttributes[] = 'brand';

@jacquesbh an evolution like this could be great yes :)

**Comment by Costa-Jeremy** [comment]
Hello everyone,

I come back to you to know if you have found a solution for this ?

Thank you in advance.
