### ISSUE TITLE
How can i add custom extra field in Documents?

### ISSUE THREAD

**Issue by atapatel** [monsieurbiz/SyliusSearchPlugin#84]
How can I add custom extra field in Documnents and use it in search?
I dont want to add it as an attribute?

**Comment by maximehuran** [comment]
See #86 with the updated README

**Comment by maximehuran** [comment]
Our new test App add some fields and the documentation available form 2.1.x  explain how to customize some filters: 

https://github.com/monsieurbiz/SyliusSearchPlugin/blob/master/docs/add_custom_values.md
https://github.com/monsieurbiz/SyliusSearchPlugin/blob/master/docs/add_custom_filters.md

Upgrade guide : 

https://github.com/monsieurbiz/SyliusSearchPlugin/blob/master/UPGRADE-2.0.md
