### ISSUE TITLE
Filters problem on resultSet

### ISSUE THREAD

**Issue by Quentin-Wuattier** [monsieurbiz/SyliusSearchPlugin#87]
Hello everyone,

Sometimes my search returns many filters on the resultSet.
My code and my label on the filters are the same.
![Capture d’écran 2021-04-01 à 11 33 12](https://user-images.githubusercontent.com/81762804/113312284-6c3fab00-930a-11eb-9ec2-1923d491cad9.png)

But when I click on a filter choice, my label goes back to normal with my selected value
![Capture d’écran 2021-04-01 à 11 39 38](https://user-images.githubusercontent.com/81762804/113312368-7f527b00-930a-11eb-95b2-f81538ff7aec.png)

Someone has already encountered this problem?

**Comment by maximehuran** [comment]
Can you install v2 plugin and try again ?
If you still have the issue, feel free to open a new issue and with more context.
